[project]
name = "my-cool-project"
version = "0.1.0"
dependencies = [
    "aiofiles>=24.1.0",
    "aiohttp>=3.12.15",
    "ijson>=3.4.0",
    "matplotlib>=3.10.5",
    "ruff>=0.12.8",
]

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

